name: steemkr
description: Korean Steem Project
version: 1.0.0
homepage: http://www.steemkr.or.kr
author: Young Gyu Park <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  angular_router: ^2.0.0-alpha+20
  angular_forms: ^2.1.0
  built_value: ">=6.2.0 <7.0.0"
  http: ">=0.11.3 <0.12.0"
  stream_transform: ^0.0.14+1
  google_maps: ">=3.3.2 <4.0.0"
  dart_browser_loader: ">=0.0.5 <0.1.0"
  google_maps_markerclusterer: ">=0.1.2 <1.0.0"
  sass_builder: ^2.1.2
  jsonrpc2: ">=2.0.0 <3.0.0"
  english_words: ^3.1.4
  firebase: ">=5.0.2 <6.0.0"
  service_worker: ^0.2.3
  logging: ^0.11.3+2

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3+3
  build_web_compilers: ^0.4.4+2
  test: ^1.5.1+1
